<a href="https://colab.research.google.com/github/davidgoins236/public/blob/main/Pandas_Data_Exploration_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice Data Exploration:
https://www.youtube.com/watch?v=9m4n2xVzk9o&t=124s

In [ ]:
import pandas as pd
import numpy as np 
import pandas_profiling
#!pip3 install pandas_profiling --upgrade
#pull HTML Table data
html = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2019_per_game.html')
#So type(html) tells me this is a list
#this turns the first list item into a pandas data frame
df2019 = html[0]

raw = df2019.drop(df2019[df2019.Age == 'Age'].index)
raw

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

This Acronyms bit was stolen from the tutorial, kept it as a good example of markup

## **Acronyms**


Acronym | Description
---|---
Rk | Rank
Pos | Position
Age | Player's age on February 1 of the season
Tm | Team
G | Games
GS | Games Started
MP | Minutes Played Per Game
FG | Field Goals Per Game
FGA | Field Goal Attempts Per Game
FG% | Field Goal Percentage
3P | 3-Point Field Goals Per Game
3PA | 3-Point Field Goal Attempts Per Game
3P% | FG% on 3-Pt FGAs.
2P | 2-Point Field Goals Per Game
2PA | 2-Point Field Goal Attempts Per Game
2P% | FG% on 2-Pt FGAs.
eFG% | Effective Field Goal Percentage
| *(Note: This statistic adjusts for the fact that a 3-point field goal is worth one more point than a 2-point field goal.)*
FT | Free Throws Per Game
FTA | Free Throw Attempts Per Game
FT% | Free Throw Percentage
ORB | Offensive Rebounds Per Game
DRB | Defensive Rebounds Per Game
TRB | Total Rebounds Per Game
AST | Assists Per Game
STL | Steals Per Game
BLK | Blocks Per Game
TOV | Turnovers Per Game
PF | Personal Fouls Per Game
PTS | Points Per Game

In [ ]:
#lets check out this pandas profiling data exploration
#https://www.youtube.com/watch?v=Ef169VELt5o
#!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
#profile  = pandas_profiling.ProfileReport(df,title = 'Pandas Profiling Report', html={'style':{'full_width':True}})
profile_min = pandas_profiling.ProfileReport(df,minimal=True)

Note: this profile report is cool, but you need to trim down your data frame before running because it becomes unmanageable

In [ ]:
#invoke the report
profile_min.to_file("nba_report.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
raw

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

### Cleaning our data

In [ ]:
raw.shape #count rows & cols, Question: why not raw()
raw.head() 
raw.isnull().sum() #figure out how many null values we have by column

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        6
3P         0
3PA        0
3P%       47
2P         0
2PA        0
2P%       15
eFG%       6
FT         0
FTA        0
FT%       43
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [ ]:
#replace NA with 0
df = raw.fillna(0)
#test with: df.isnull().sum()
#remove the rank variable
df = df.drop(['Rk'],axis = 1)

In [ ]:
#setup notebook to show all rows of the data
#pd.set_option('display.max_rows',df.shape[0]+1)
#revert to default
pd.set_option('display.max_rows',50)
df

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,.357,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,.222,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,.345,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,.595,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,.576,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,.571,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,.553,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,.559,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,.580,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,.538,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [ ]:
#df.select_dtypes(include=['object'])
#df.dtypes

#okay so it looks like the fastest way to fix all these 'object' data types is to save and reload as csv
df.to_csv("nba.csv")
#now pull it back in and check dtypes
df = pd.read_csv("nba.csv")
df.dtypes

Unnamed: 0        int64
Unnamed: 0.1      int64
Player           object
Pos              object
Age               int64
Tm               object
G                 int64
GS                int64
MP              float64
FG              float64
FGA             float64
FG%             float64
3P              float64
3PA             float64
3P%             float64
2P              float64
2PA             float64
2P%             float64
eFG%            float64
FT              float64
FTA             float64
FT%             float64
ORB             float64
DRB             float64
TRB             float64
AST             float64
STL             float64
BLK             float64
TOV             float64
PF              float64
PTS             float64
dtype: object

In [ ]:
#who has the most points
df[df.PTS==df.PTS.max()]
#who are the top k players for x
df.nlargest(10,'STL')

,Unnamed: 0,Unnamed: 0.1,Player,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
103,103,107,Jimmy Butler,SG,29,MIN,10,10,36.1,7.4,...,0.787,1.6,3.6,5.2,4.3,2.4,1.0,1.4,1.8,21.3
149,149,154,Robert Covington,SF,28,MIN,22,22,34.7,4.8,...,0.773,1.0,4.8,5.7,1.5,2.3,1.1,1.1,3.7,14.5
243,243,252,Paul George,SF,28,OKC,77,77,36.9,9.2,...,0.839,1.4,6.8,8.2,4.1,2.2,0.4,2.7,2.8,28.0
147,147,152,Robert Covington,SF,28,TOT,35,35,34.4,4.5,...,0.764,0.8,4.7,5.5,1.3,2.1,1.3,1.3,3.6,13.3
270,270,280,James Harden,PG,29,HOU,78,78,36.8,10.8,...,0.879,0.8,5.8,6.6,7.5,2.0,0.7,5.0,3.1,36.1
531,531,550,Chris Paul,PG,33,HOU,58,58,32.0,5.2,...,0.862,0.6,3.9,4.6,8.2,2.0,0.3,2.6,2.5,15.6
102,102,106,Jimmy Butler,SF-SG,29,TOT,65,65,33.6,6.4,...,0.855,1.9,3.4,5.3,4.0,1.9,0.6,1.5,1.7,18.7
675,675,700,Russell Westbrook,PG,30,OKC,73,73,36.0,8.6,...,0.656,1.5,9.6,11.1,10.7,1.9,0.5,4.5,3.4,22.9
104,104,108,Jimmy Butler,SF,29,PHI,55,55,33.2,6.3,...,0.868,1.9,3.4,5.3,4.0,1.8,0.5,1.5,1.7,18.2
148,148,153,Robert Covington,SF,28,PHI,13,13,33.8,3.8,...,0.739,0.5,4.6,5.2,1.1,1.8,1.8,1.7,3.5,11.3

In [ ]:
#how many player(s) score > 20 points per game
df[df.PTS>20].shape[0] #nrows() equivalent - how many players score > 20

37

In [ ]:
#who scores>20
df[df.PTS>20].loc[:,['Player','Pos','Tm','PTS']].sort_values('PTS',ascending = False) #.loc works a bit like select()

In [ ]:
#tutorial question: which player had the highest 3 pt fg per game
df[df['3P']==df['3P'].max()]
#which player lead assits
df.nlargest(10,'AST').sort_values('AST',ascending = False).loc[:,['Player','Pos','Tm','3P','PTS','AST']]

                Player Pos   Tm   3P   PTS   AST
675  Russell Westbrook  PG  OKC  1.6  22.9  10.7
411         Kyle Lowry  PG  TOR  2.4  14.2   8.7
668          John Wall  PG  WAS  1.6  20.7   8.7
335       LeBron James  SF  LAL  2.0  27.4   8.3
531         Chris Paul  PG  HOU  2.2  15.6   8.2
631        Jeff Teague  PG  MIN  0.8  12.1   8.2
699         Trae Young  PG  ATL  1.9  19.1   8.1
569        Rajon Rondo  PG  LAL  1.1   9.2   8.0
301       Jrue Holiday  SG  NOP  1.8  21.2   7.7
599        Ben Simmons  PG  PHI  0.0  16.9   7.7

In [ ]:
#Which player had 2nd most points on the Lakers
lal=df[df['Tm']=='LAL']
lal.sort_values('PTS',ascending = False).iloc[[1]] #note: pandas starts counting at 0

,Unnamed: 0,Unnamed: 0.1,Player,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
383,383,397,Kyle Kuzma,PF,23,LAL,70,68,33.1,7.1,...,0.752,0.9,4.6,5.5,2.5,0.6,0.4,1.9,2.4,18.7

In [ ]:
#which position scores most
position = df.groupby('Pos').PTS.describe()
position[position['count']>5].sort_values('mean',ascending=False)

     count      mean       std  min    25%   50%     75%   max
Pos
C    120.0  8.785000  5.616582  0.0  4.175  7.75  12.350  27.5
PG   139.0  8.668345  6.284234  0.0  4.300  7.00  11.050  36.1
SG   174.0  8.487356  5.724974  0.0  4.000  7.65  11.275  26.6
SF   120.0  8.259167  5.935203  0.0  4.200  6.70  11.600  28.0
PF   147.0  7.703401  5.622380  0.0  3.350  6.30  11.100  27.7

### Questions:
- Top Correlates of PT
- Predict PTS
- Predict Position